io:
  input:
    file: file://${project.basedir}/src/test/resources/in/*.dat
    delimiter: รง
    chunk: 50
    skipLimit: 10
    salesmanLineId: "001" 
    customerLineId: "002"
    saleLineId: "003"
    
  output:
    dir: src/test/resources/out/
    extension: .done.dat
    delimiter: ;
      
spring:
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:batchcontroldb;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: pass
    initialization-mode: always
