io:
  input:
    file: file://${user.home}/data/in/*.dat
    delimiter: รง
    chunk: 50
    skipLimit: 10
    salesmanLineId: "001" 
    customerLineId: "002"
    saleLineId: "003"
    
  output:
    dir: ${user.home}/data/out/
    extension: .done.dat
    delimiter: ;
    header:
      customersQuantity: QUANTIDADE_CLIENTES
      sellersQuantity: QUANTIDADE_VENDEDORES
      biggestSale: ID_VENDA_MAIOR_VALOR
      worstSeller: PIOR_VENDEDOR
      
batch:
  schedulerInMilliseconds: 60000
  
spring:
  data:
    mongodb:
      database: batch_db
      port: 27017
      host: localhost
      #username: 
      #password:
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:batchcontroldb;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: pass
    initialization-mode: always