io:
  input:
    file: file://${user.home}/data/in/*.dat
    delimiter: รง
    salesMan:
      lineId: "001" 
    customer:
      lineId: "002"
    sales:
      lineId: "003"
    
  output:
    dir: ${user.home}/data/out/
    type: .done.dat
    delimiter: ;
    header:
      customersQuantity: QUANTIDADE_CLIENTES
      sellersQuantity: QUANTIDADE_VENDEDORES
      biggestSale: ID_VENDA_MAIOR_VALOR
      worstSeller: PIOR_VENDEDOR

batch:
  schedulerInMilliseconds: 300000