io:
  input:
    file: file://${user.home}/data/in/*.dat
    delimiter: รง
    salesmanLineId: "001" 
    customerLineId: "002"
    saleLineId: "003"
    
  output:
    dir: ${user.home}/data/out/
    extension: .done.dat
    delimiter: ;
    header:
      customersQuantity: QUANTIDADE_CLIENTES
      sellersQuantity: QUANTIDADE_VENDEDORES
      biggestSale: ID_VENDA_MAIOR_VALOR
      worstSeller: PIOR_VENDEDOR
      
batch:
  schedulerInMilliseconds: 60000
